// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx-H45J4Ygf7MoZW7tNoQP3DV0DTdpURA',
    appId: '1:501806345297:web:b5221c6c7134b285dbdc70',
    messagingSenderId: '501806345297',
    projectId: 'crafter-code',
    authDomain: 'crafter-code.firebaseapp.com',
    storageBucket: 'crafter-code.appspot.com',
    measurementId: 'G-X1GW4S7RRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8b3V5YIB6OkkMUseqAcrTd2rZmQLnmWY',
    appId: '1:501806345297:android:a27ff4b134d7a871dbdc70',
    messagingSenderId: '501806345297',
    projectId: 'crafter-code',
    storageBucket: 'crafter-code.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb2n_-AR8-d7lnNjFneJ5yXuY7ee_xSFc',
    appId: '1:501806345297:ios:4e74af6293dd9594dbdc70',
    messagingSenderId: '501806345297',
    projectId: 'crafter-code',
    storageBucket: 'crafter-code.appspot.com',
    iosBundleId: 'com.example.crafterCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb2n_-AR8-d7lnNjFneJ5yXuY7ee_xSFc',
    appId: '1:501806345297:ios:4e74af6293dd9594dbdc70',
    messagingSenderId: '501806345297',
    projectId: 'crafter-code',
    storageBucket: 'crafter-code.appspot.com',
    iosBundleId: 'com.example.crafterCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx-H45J4Ygf7MoZW7tNoQP3DV0DTdpURA',
    appId: '1:501806345297:web:7af232ec2e6df2b2dbdc70',
    messagingSenderId: '501806345297',
    projectId: 'crafter-code',
    authDomain: 'crafter-code.firebaseapp.com',
    storageBucket: 'crafter-code.appspot.com',
    measurementId: 'G-KNKYBPXH32',
  );
}
