// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTxgmw_yckteDiwvFSC7wPxxeZ4biImsg',
    appId: '1:102008231057:web:403d8e7f59ec08379a1b30',
    messagingSenderId: '102008231057',
    projectId: 'class-management-64193',
    authDomain: 'class-management-64193.firebaseapp.com',
    storageBucket: 'class-management-64193.appspot.com',
    measurementId: 'G-Q6KL47W8D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0BZyrmljsIqz-J2JRZV_Mtjken8JIsH8',
    appId: '1:102008231057:android:d27ff2accc08d0079a1b30',
    messagingSenderId: '102008231057',
    projectId: 'class-management-64193',
    storageBucket: 'class-management-64193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwA2XuSpjH8K7iuJJC53aooBmqKE_8eCU',
    appId: '1:102008231057:ios:918a3c9a49d3841f9a1b30',
    messagingSenderId: '102008231057',
    projectId: 'class-management-64193',
    storageBucket: 'class-management-64193.appspot.com',
    iosBundleId: 'com.example.classManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwA2XuSpjH8K7iuJJC53aooBmqKE_8eCU',
    appId: '1:102008231057:ios:918a3c9a49d3841f9a1b30',
    messagingSenderId: '102008231057',
    projectId: 'class-management-64193',
    storageBucket: 'class-management-64193.appspot.com',
    iosBundleId: 'com.example.classManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTxgmw_yckteDiwvFSC7wPxxeZ4biImsg',
    appId: '1:102008231057:web:5b66a77d0c06bd9f9a1b30',
    messagingSenderId: '102008231057',
    projectId: 'class-management-64193',
    authDomain: 'class-management-64193.firebaseapp.com',
    storageBucket: 'class-management-64193.appspot.com',
    measurementId: 'G-QZS4FWTXN5',
  );

}